### ISSUE TITLE
第1回ミーティング：機能洗い出し

### ISSUE THREAD

**Issue by himu62** [hearb/hearb#1]
@hearb/designers, @hearb/engineers, @hearb/managers 

機能の洗い出し、具体的な実装プロセスを発案する場を設けます。

## 事前準備

類似サービスの分析。
アイデアをなんとなくでいいので考えておいてください。

## 日時

4/15 (金) 16:00〜19:00

*ネトラボが取れなかった場合→4/15 (金) 19:00〜21:00*
*終了時間は前後すると思います。*

## 場所

ネットワークラボ

## 参加確認

参加できる場合はチェックしてください。
これをもって確定とします。
できない場合は、このIssueにコメントして、参加できる日時を言ってください。

**確定日時：4/15 (金) 13:55**

- [x] 沼田さん
- [x] 小林
- [x] すっぴー
- [x] あっきー
- [ ] 江原くん

**Comment by koichi123** [comment]
4/15日は17時から就活がある為、終わりの方の参加になります。
もしくは、19時からなら参加できます。

**Comment by himu62** [comment]
@hearb/designers, @hearb/engineers, @hearb/managers

日程調整の結果、
**4/28 (木) 16:00〜18:00**
に変更します。
場所は**ネトラボ**、空いていなければ**自習室**で行います。

====
確認だけお願いします。
急用などで参加できなくなった場合には、LINEで連絡してください。

- [x] 沼田さん
- [x] 小林
- [ ] すっぴー
- [ ] あっきー
- [ ] 江原くん
