### ISSUE TITLE
プライバシーポリシーの作成

### ISSUE THREAD

**Issue by himu62** [hearb/hearb#10]
Facebookにアプリ登録する際に必要になる、プライバシーポリシーをつくる。

いろんなサービスのプライバシーポリシーを参考に、テキストを起こして、ここにファイル添付してください。

**Comment by himu62** [comment]
プライバシーポリシーに加え、利用規約も作成する。

プライバシーポリシーでは、「どんな情報を」「誰が」「どんな目的で」取得するか明示する。

[個人情報](https://ja.wikipedia.org/wiki/個人情報)……………個人を特定できる情報
プライバシー情報…組み合わせることで個人を特定し得る情報
パーソナル情報……個人は特定できないが、本人が公開を望まない情報

**Comment by numata0409** [comment]
場所　：　googleドライブ HEARB

利用規約草案
プライバシーポリシー草案

２つの草案を作ったので確認してみてください。
初めて作ったので確実に漏れがあるので洗い出していきましょ！
