### ISSUE TITLE
ロゴの作成

### ISSUE THREAD

**Issue by himu62** [hearb/hearb#9]
サービスのロゴ画像をつくる。

## 要件
- 72dpi, RGB 8bit
- サイズは500x500pixel以上
- 100x100pixel程度に縮小しても可視性に優れていること
- データはPSDファイルまたはAIファイル

**Comment by suppy1026** [comment]
[hearb_logo.zip](https://github.com/hearb/hearb/files/295857/hearb_logo.zip)
